[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_escrow = "8smRpvsA5XA1fwNSv81sbQw8LgEVSjvncoTSZv6xUP12"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

create-task-queue = "tuktuk -u http://127.0.0.1:8899 task-queue create --name future-task --capacity 100 --funding-amount 200000000 --queue-authority ALH8UD28X24qwGvG2kpTcogg3Wpvu31FrErpLU8vw6oT --min-crank-reward 1000000 --stale-task-age 100000000 "
fund-task-queue = "tuktuk -u http://127.0.0.1:8899 task-queue fund --task-queue-name future-task --amount 200000000"
test-list = "tuktuk -u http://127.0.0.1:8899 task list --task-queue-name future-task"


cron = "bun run ts-node cron/cron.ts --taskQueue CJv1jLvFSLsV7X1UGq6bHr6XHacbJAfq7Tio8iqpEK6b --weekSeconds 4 --staleSeconds 604800 --batchSize 100"
cron-once = "bun run ts-node cron/cron.ts --taskQueue CJv1jLvFSLsV7X1UGq6bHr6XHacbJAfq7Tio8iqpEK6b --runOnce true --staleSeconds 604800 --batchSize 100"

cron-list = "tuktuk -u http://127.0.0.1:8899 cron list"

add-queue-authority="tuktuk -u http://127.0.0.1:8899 task-queue add-queue-authority --task-queue-name future-task --queue-authority ALH8UD28X24qwGvG2kpTcogg3Wpvu31FrErpLU8vw6oT"

cron-t-list= "tuktuk -u http://127.0.0.1:8899 cron-transaction list --cron-name "